# is a organization repository
organization: false

# site title
title: Mirror

# github user
user: LoeiFy

# issue repository
repository: Recordum

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 5#c21bffc137f44faf7e9c4a84da827f7cc2cfeaa

# posts per page
perpage: 7
